### ISSUE TITLE
pluginsRoot not an array

### ISSUE THREAD

**Issue by danosaure** [shootaroo/jit-grunt#26]
When defining pluginsRoot, it seems like it is not checking parents' node_modules directory as it should. I do have the latest version.

Here is my situation, that may or may not be covered under the release notes for parent node_modules checking.

I have a common module (say "shared-grunt") that my project depends on. When I have a common dependency (say grunt-contrib-requirejs for my current issue), the jit-grunt is configured inside "shared-grunt" module with pluginsRoot set as absolute path with __dirname. But then, we get error that jit-grunt cannot find a plugin.

Thanks.

**Comment by shootaroo** [comment]
Does it mean jit-grunt should always check `node_modules` directory even if `pluginsRoot` was defined?

**Comment by danosaure** [comment]
Sorry, I didn't get that notice earlier.

What I would like is that when i define `pluginsRoot`, it will still check `node_modules`, and parent `node_modules` directories. So the situation below is covered:

- node_modules
    - shared-grunt
        - Gruntfile.js
        - node_modules
            - grunt-contrib-clean
            - jit-grunt
    - current-project-dependency

With this, I do not know how to configure to be able to have access to both `grunt-contrib-clean`, and `current-project-dependency`.

I have put into `shared-grunt` a lot of the reused configuration for so many projects. But then, not all project would say, use `current-project-dependency`.

Hope this clarifies the situation.

**Comment by danosaure** [comment]
With an `Array`, I would be able to define in my `shared-grunt`:

    [
        __dirname + 'node_modules',
        process.cwd() + 'node_modules',
    ]

**Comment by shootaroo** [comment]
I do not feel like supporting array of `pluginsRoot`. Please try the `node_modules-always` brunch.
```
$ npm install http://github.com/shootaroo/jit-grunt/tarball/node_moduels-always
```

```js
require('jit-grunt')(grunt)({
  pluginsRoot: __dirname + '/node_modules'
});
```
Always find the `node_modules` directory.

**Comment by schmod** [comment]
This is going to start becoming an issue with NPM 3.x, as the directory hierarchy of the packages that NPM installs has changed.  

In my particular use-case, I have a module full of the various grunt configurations and plugins that I use across a variety of front-end projects that I work on.

In practice, it's a little more complicated than this, but a typical frontend project for me includes `build-tools` as a module in its `package.json', and NPM 2.x would give me a directory structure like this: 

```tree
my_website
└── node_modules
    └── build-tools
        └── node_modules
            ├── grunt-uglify
            └── grunt-contrib-clean
```

Typically, jit-grunt can't deal with this structure unless I define `build-tools` as the pluginsRoot:

```js
require('jit-grunt')(grunt)({
  pluginsRoot: 'node_modules/build-tools/node_modules'
});
```

However, the flat hierarchy produced by NPM 3 is different:

```
my_website
└── node_modules
    ├── grunt-uglify
    ├── grunt-contrib-clean
    └── build-tools
```

As you can tell, this is actually a lot closer to the "ideal," and I can actually remove the `pluginsRoot` configuration, albeit at the expense of breaking support for NPM 2.x (which is still quite common).

A naive hack might be to sniff to detect whether or not `build-tools` has a `node_modules` folder of its own, but this is still theoretically valid under NPM 3 -- both as legacy support for NPM 2.x users, as well as to support edge-cases where `my_website` and `build-tools` might request conflicting versions of the same package:

```
my_website
└── node_modules
    ├── grunt-uglify@0.2
    └── build-tools
        └── node_modules
            ├── grunt-uglify@0.3
            └── grunt-contrib-clean
```

Ideally, instead of having `pluginsRoot` point at the exact location of a `node_modules` folder, it would make more sense for the value to be a base directory from which packages are resolved via Node's standard resolution algorithm for loading a module via `require()`  (ie. [`require.resolve()`](https://github.com/substack/node-resolve)), traversing up the filesystem as necessary.

**Comment by schmod** [comment]
Wait a second.  I literally implemented the exact thing you're talking about above *facepalm*.  

Now I need to go figure out why it isn't working in the second scenario described above...

**Comment by danosaure** [comment]
I have moved away from this pattern, so closing this as it is not an issue anymore for me.
